### ISSUE TITLE
Immutable X - NFT Staking

### ISSUE THREAD

**Issue by rzmahmood** [immutable/imx-starknet#9]
Immutable X seeks to support the StarkNet community by creating primitives which can help blockchain games find success. 

A common requirement of NFT projects is the ability to stake NFTs. The economics behind why stake NFTs should be flexible to the project. For example, projects may want users to stake their NFTs in exchange for rewards over time.

This issue is to discuss what the design and implementation could look like for a general-purpose NFT staking contract.  It also seeks to gather requirements from existing and new projects which may be looking to implement staking into their NFT ecosystem.

Questions to the Community:
- Does your project require the ability to stake NFTs?
- What is the incentive for staking NFTs in your ecosystem?
- Would you find value in an audited and open-source NFT Staking contract or would you still roll your own, requiring Cairo capability?

**Comment by Wave-95** [comment]
Hey Rez! Awesome to see IMX leveraging the community in the design spec for NFT staking. I've developed a few .sol staking contracts for different NFT communities and here are some key observations I've made over time:

1. Users tend to prefer non-custodial staking. Especially NFT beginners, they feel uneasy about moving their NFT into a staking contract and seeing their NFT "disappear" from their OpenSea profile. Non-custodial route tends to be the preferred path as NFT users often aren't savvy enough to understand ownership mechanics in custodial contracts. A secondary point, non-custodial staking prevents collections from having an artificially low "holders" statistic, which is a commonly referred to metric for speculators to decide if they want to invest in an NFT project. Good holder distribution = good collection. 
2. Configurable values for emission rate and rewards duration is very nice.
3. I found its quite nice to mint new ERC20 tokens from a staking contract as opposed to transferring "pre-minted" tokens. This keeps circulating supply of the ERC20 rewards token configurable through emission rate and rewards duration. I've also seen projects utilize a max supply value for ERC20 rewards to determine when rewards end. 
4. Users prefer staking rewards based on block.timestamp rather than being subjected to epochs. This gives users flexibility to stake or unstake their NFTs and immediately accrue/withdraw rewards. Of course, many project owners like to issue rewards based on certain time intervals. Ultimately project owners are the decision maker, but just presenting both sides here. Perhaps there could be a base NFT staking contract that accrues rewards based on block.timestamp, and an epoch extension that can be optionally implemented.
5. I found it's quite common to see community members demand for some type of sophisticated staking mechanic where long term stakers receive a larger portion of rewards compared to short term stakers. Perhaps this shouldn't live in the base staking contract, and also moved into an extension. 
6. Some mechanism to filter certain tokenIds (rare or genesis NFTs) such that only these NFTs can accrue rewards. Though this pattern is becoming less common (community demands fair distribution of rewards to all token holders).

I think staking is definitely a utility that NFT investors look for, and therefore NFT project owners inevitably promise staking functionality in their roadmap. From what I've seen, there has not been a great standard for NFT staking that projects utilize. I think this is in part due to the variability of what the project is trying to accomplish with staking. The staking mechanic is also always evolving, and projects tend to gravitate towards the latest NFT staking contract & fork off of it. 

To answer your third bullet point, I'm unsure how often an open-source NFT staking contract from IMX will be imported given the variability of each project's needs. But I will say it would be nice to have a simple base NFT staking contract to help developers get started and brainstorming. Even OpenZeppelin doesn't have an NFT staking standard at the moment. The current workflow is to look at what other NFT projects have done. Ultimately, I think it's a worthwhile endeavor to explore, collect community feedback, and iterate on a standard that meets a majority of projects' needs. It's also a great look for IMX to showcase how serious they are when it comes to NFTs :) 

These are just some of my initial thoughts, I'll add more as I think about them. Excited to see where this convo is headed!

**Comment by rzmahmood** [comment]
> Hey Rez! Awesome to see IMX leveraging the community in the design spec for NFT staking. I've developed a few .sol staking contracts for different NFT communities and here are some key observations I've made over time:
> 
> 1. Users tend to prefer non-custodial staking. Especially NFT beginners, they feel uneasy about moving their NFT into a staking contract and seeing their NFT "disappear" from their OpenSea profile. Non-custodial route tends to be the preferred path as NFT users often aren't savvy enough to understand ownership mechanics in custodial contracts. A secondary point, non-custodial staking prevents collections from having an artificially low "holders" statistic, which is a commonly referred to metric for speculators to decide if they want to invest in an NFT project. Good holder distribution = good collection.
> 2. Configurable values for emission rate and rewards duration is very nice.
> 3. I found its quite nice to mint new ERC20 tokens from a staking contract as opposed to transferring "pre-minted" tokens. This keeps circulating supply of the ERC20 rewards token configurable through emission rate and rewards duration. I've also seen projects utilize a max supply value for ERC20 rewards to determine when rewards end.
> 4. Users prefer staking rewards based on block.timestamp rather than being subjected to epochs. This gives users flexibility to stake or unstake their NFTs and immediately accrue/withdraw rewards. Of course, many project owners like to issue rewards based on certain time intervals. Ultimately project owners are the decision maker, but just presenting both sides here. Perhaps there could be a base NFT staking contract that accrues rewards based on block.timestamp, and an epoch extension that can be optionally implemented.
> 5. I found it's quite common to see community members demand for some type of sophisticated staking mechanic where long term stakers receive a larger portion of rewards compared to short term stakers. Perhaps this shouldn't live in the base staking contract, and also moved into an extension.
> 6. Some mechanism to filter certain tokenIds (rare or genesis NFTs) such that only these NFTs can accrue rewards. Though this pattern is becoming less common (community demands fair distribution of rewards to all token holders).
> 
> I think staking is definitely a utility that NFT investors look for, and therefore NFT project owners inevitably promise staking functionality in their roadmap. From what I've seen, there has not been a great standard for NFT staking that projects utilize. I think this is in part due to the variability of what the project is trying to accomplish with staking. The staking mechanic is also always evolving, and projects tend to gravitate towards the latest NFT staking contract & fork off of it.
> 
> To answer your third bullet point, I'm unsure how often an open-source NFT staking contract from IMX will be imported given the variability of each project's needs. But I will say it would be nice to have a simple base NFT staking contract to help developers get started and brainstorming. Even OpenZeppelin doesn't have an NFT staking standard at the moment. The current workflow is to look at what other NFT projects have done. Ultimately, I think it's a worthwhile endeavor to explore, collect community feedback, and iterate on a standard that meets a majority of projects' needs. It's also a great look for IMX to showcase how serious they are when it comes to NFTs :)
> 
> These are just some of my initial thoughts, I'll add more as I think about them. Excited to see where this convo is headed!

Thanks for the thoughts @Wave-95 ! This is super valuable for us to understand. I 100% agree with the custodianship issue. We could likely explore extending ERC721 with a 'Stakeable_ERC721' extension, which locks up the NFT, preventing it from being transferred, but still maintaining `owner` information. Have you found that most contracts simply block `transferFrom` while staked or is there more developed mechanics around this?

Again, appreciate your thoughts! 🙌
